### ISSUE TITLE
Peer feedback for projects popup

### ISSUE THREAD

**Issue by Elerqsousy** [saied2035/mobile-version-skeleton#12]
- use popup background-size instead of distorting the image size
- responsive popup creation through using different styling of mobile and desktop version, instead of declaring

**Comment by Bavon101** [comment]
@saied2035 Your project looks great🐱‍💻 I also like your` .js` logic for pop up. I think your project details pop-up window will be more responsive if you used `.css class` than runtime specification for both desktop and mobile view.🐱‍🏍

**Comment by saied2035** [comment]
Thank to all of you for your comments I will work on it.
