### ISSUE TITLE
Peer Review No.1 - on PR-3

### ISSUE THREAD

**Issue by ahangarha** [saied2035/mobile-version-skeleton#4]
Peer Review on Pull Request https://github.com/saied2035/mobile-version-skeleton/pull/3

**Comment by thenarain** [comment]
You have done a great job. Your code works fine and the code quality is as per standard. It is advisable to keep all the images in a separate folder to make them more organized.

**Comment by Mehdi-Rh** [comment]
Texts and titles should have a left and right margin
![Screenshot from 2022-01-11 08-35-26](https://user-images.githubusercontent.com/62058680/148900405-1d1ea7cc-3eba-4407-9a58-b5b439dbc7ba.png)

**Comment by saied2035** [comment]
thanks for all of you. I will consider these coomments too improve my code.

**Comment by ahangarha** [comment]
You have done a very good job. Most of the things are made very much close to the design. I see some issue (like those pointed by Mehdi) but those are in other sections and not related to this particular PR.

Frankly there is nothing problematic in this PR. Yet I see:
- Extra space in HTML indentation after line 60
- I suggest to use 2 spaces for indentation not 4 (in html)

There are some spacing and alignment issues in other parts of the project which is not related to this commit so I don't mention them.

Again, you did good job :+1:
